name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd PortalUIAutomation
          npm install

      - name: Install Playwright Browsers
        run: |
          cd PortalUIAutomation
          npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          PW_HEADLESS: 1
        run: |
          cd PortalUIAutomation
          xvfb-run npx cucumber-js features/LoginTest.feature --tags "@Dashboard" --format allure-cucumberjs/reporter || true
          xvfb-run npx cucumber-js features/Dashboard.feature --tags "@Dashboard" --format allure-cucumberjs/reporter || true
          xvfb-run npx cucumber-js features/Refund.feature --tags "@Refund" --format allure-cucumberjs/reporter || true
          xvfb-run npx cucumber-js features/Transactions.feature --tags "@Transactions" --format allure-cucumberjs/reporter || true
          xvfb-run npx cucumber-js features/Settlement.feature --tags "@Settlement" --format allure-cucumberjs/reporter || true
          xvfb-run npx cucumber-js features/InstantSettlement.feature --tags "@InstantSettlement1" --format allure-cucumberjs/reporter || true
         
      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Unified Report
        if: always()
        run: |
          allure generate PortalUIAutomation/allure-results --clean --single-file -o allure-report

      - name: Upload Raw Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: PortalUIAutomation/allure-results/

      - name: Upload Unified HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-allure-report
          path: allure-report/
